### PR TITLE
Settings to disable some maps

### PR DESCRIPTION
**Pull request by jazzzz**
On Firefox:

image

On Chrome:

image

### CODE REVIEW

**Comment by tankaru** [comment]
When I run 'npm run build', 
"default_popup": "popup/popup.html" in manifest.json
is changed to
"default_popup":"popup\popup.html" in dist/manifest.json
and Chrome/Firefox says it's invalid JSON.
(Windows10, npm 6.4.1)

Do you know its reason?

**Comment by jazzzz** [comment]
It's probably because you are under Windows. Maybe an issue with parcel-plugin-web-extension, I will look into it.

**Comment by jazzzz** [comment]
I found the bug: kevincharm/parcel-plugin-web-extension#14. Unfortunately it's still not fixed, I will see what can be done.

**Comment by jazzzz** [comment]
I made a workaround, it should now build correctly under Windows.

**Comment by tankaru** [comment]
Thanks! 
Great work again!
I will publish it for Chrome/FF soon.
And I will add more maps to this plugin later.

**Pull request merged**
